version: "3.9"

services:
  magic_magnet_python:
    #network_mode: "host"        
    build: 
      context: ./
      dockerfile: ./Dockerfile_magic_magnet_python
    image: yingshaoxo/static_magic_magnet_python
    volumes:
      - "./data:/build2"
    restart: "no"
    #restart: unless-stopped
