version: "3.9"

services:
  webpage_chat_application:
    network_mode: "host"        
    image: python:3.4-alpine
    volumes:
      - ".:/code/back_end"
    working_dir: /code/back_end
    command: sh -c "python -u main.py"
    restart: unless-stopped
