version: "3.9"

services:
  yppm_question_and_answer_community:
    #0.0.0.0:54321
    network_mode: "host"        
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: yingshaoxo/yppm_question_and_answer_community
    #environment:
    #  - ADMIN_EMAIL=yingshaoxo@gmail.com
    volumes:
      - "./database_data:/code/back_end/database_data"
      - "./yingshaoxo_chat_data:/code/back_end/yingshaoxo_chat_data"
    restart: unless-stopped
